### PR TITLE
[ble] Fixed regression the UUIDs were not found

### LINKED ISSUE #1869: [BLE] Primary Service UUID not found
### Description

 This is a regression issue, after zephyr updated to 1.11. Primary Service UUID cannot find. I cannot use nRF app or WebBlueTooth(https://goo.gl/QEvyDZ) to communication with Arduino101.

### Test Code

[BLE.js](https://github.com/intel/zephyr.js/blob/master/samples/BLE.js);
[WebBluetoothDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/WebBluetoothDemo.js);
[WebBluetoothGroveLcdDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js); 
[HeartRateDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/HeartRateDemo.js); 
[SensorBLEDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/SensorBLEDemo.js)
[test-ble.js](https://github.com/intel/zephyr.js/blob/master/tests/test-ble.js)

### Steps to Reproduction

Scenario 1:
1. `make JS=samples/BLE.js ROM=256`
2. `make dfu`
3. connect Arduino101 with nRF app

Scenario 2:
1. `make JS=samples/WebBluetoothDemo.js ROM=256`
2. `make dfu`
3. connect Arduino101 with WebBlueTooth(https://goo.gl/QEvyDZ)

### Actual Result

Scenario 1:
screenshot_20180411-053901

Scenario 2:
screenshot_20180411-043741

### Expected Result

Scenario 1:
screenshot_20180411-223605

Scenario 2:
screenshot_20180411-230454

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result | Comment
---|---|---|---|---|---
master | 3f8eb85| Arduino 101 | Apr 11, 2017 | Pass |
master | d5d5540 | Arduino 101 | Apr 11, 2017 | Fail |

### PR DESCRIPTION
**Pull request by jimmy-huang**
This was caused by the bt_uuid struct was not properly allocated
memory to store the bits.

Fixes #1869

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

File: src/zjs_ble.c [hunk 1]
```diff
@@ -84,6 +84,11 @@ typedef struct zjs_ble_handle {
     ble_connection_t *connections;
 } ble_handle_t;
 
+static struct bt_uuid *gatt_primary_service_uuid = BT_UUID_GATT_PRIMARY;
+static struct bt_uuid *gatt_characteristic_uuid = BT_UUID_GATT_CHRC;
+static struct bt_uuid *gatt_cud_uuid = BT_UUID_GATT_CUD;
+static struct bt_uuid *gatt_ccc_uuid = BT_UUID_GATT_CCC;
```
Comment (grgustaf) [inline src/zjs_ble.c]: Why define this one if it's not used?

Comment (jimmy-huang) [reply src/zjs_ble.c]: fixed

**Comment by grgustaf** [comment]
+1
