### PR TITLE
[gfx] Can set coordinate as negative number

### LINKED ISSUE #1744: [gfx] When I set coordinate as negative number, the coordinate has be fixed to zero.
### Description

When I set coordinate as negative number, the coordinate has be fixed to zero.
 

### Test Code

Simple test:
```
var LCD = require("ST7735.js");
var board = require("board");
var drawImmediate = board.name === "arduino_101" ? true : false;
var gfxLib = require("gfx");

var GFX = gfxLib.init(LCD.width, LCD.height, LCD.initScreen, LCD.drawCB, drawImmediate, LCD);

var BLACK =  [0x00, 0x00];
var WHITE =  [0xFF, 0xFF];

GFX.fillRect(0, 0, 128, 160, BLACK);

GFX.drawLine(-50, 30, -90, 100, WHITE);
GFX.drawLine(30, -50, 100, -90, WHITE);
```

 

### Actual Result

Line1: Starting point： [0, 30], End point： [0, 100]
Line2: Starting point： [30, 0], End point： [100, 0]
 

### Expected Result

Outside of screen and don't display.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | b17a496 | Arduino 101 | Jan 9, 2018 | Fail

### PR DESCRIPTION
**Pull request by cuiyanx**
Fixed #1744 

Signed-off-by: Cui Yan <yanx.cui@intel.com>

### CODE REVIEW

File: src/zjs_gfx.c [hunk 1]
```diff
@@ -96,44 +96,60 @@ static void args_to_data(gfx_data_t *data, u32_t argc, const jerry_value_t argv[
...
     gfxHandle->touched = false;
 }
 
-static void zjs_gfx_touch_pixels(u32_t x, u32_t y, u32_t w, u32_t h, u8_t color[], gfx_handle_t *gfxHandle)
+static void zjs_gfx_touch_pixels(int32_t x, int32_t y, u32_t w, u32_t h, u8_t color[], gfx_handle_t *gfxHandle)
 {
     // Check that x and y aren't past the screen
-    if (x >= gfxHandle->screenW || y >= gfxHandle->screenH)
+    if (x >= gfxHandle->screenW || y >= gfxHandle->screenH || (int32_t)(x + w) <= 0 || (int32_t)(y + h) <= 0) {
+        zjs_gfx_reset_touched_pixels(gfxHandle);
```
Comment (brianjjones) [inline src/zjs_gfx.c]: We shouldn't reset the touched pixels if something is drawn off screen.  Take for example if we are drawing in flush mode, and we have several things being drawn.  Just because some of them are off screen doesn't mean we shouldn't draw the rest.

File: src/zjs_gfx.c [hunk 2]
```diff
@@ -96,44 +96,60 @@ static void args_to_data(gfx_data_t *data, u32_t argc, const jerry_value_t argv[
...
-            gfxHandle->tpX1 = gfxHandle->screenW - 1;
-            w = gfxHandle->tpX1 - x;
+            gfxHandle->tpX0 = 0;
+            gfxHandle->tpX1 = gfxHandle->screenW;
         }
     }
-
-    if (gfxHandle->tpY0 > y) {
-        gfxHandle->tpY0 = y;
+    else if (x >= 0 && x < gfxHandle->screenW) {
```
Comment (brianjjones) [inline src/zjs_gfx.c]: No need for x >=0 check here, its already guaranteed since x < 0 is false.

**Comment by brianjjones** [comment]
@cuiyanx Other than my two minor comments it looks good.  Fix those and it will be good to go, thanks.

**Comment by grgustaf** [comment]
@cuiyanx or @brianjjones can you fix the conflicts here?

**Comment by cuiyanx** [comment]
@grgustaf Fixed with ba69d2ad.

**Comment by grgustaf** [comment]
@cuiyanx can you force push over this branch with the new commit?

**Comment by cuiyanx** [comment]
@grgustaf OK, with commit f51fcc3b0 on master.

**Comment by brianjjones** [comment]
@grgustaf LGTM +1

**Comment by grgustaf** [comment]
+1
